Release Spleeter: Split audio item into stems v1.1
ReaTeam/ReaScripts pull request #1386
Opened 2024-05-12 13:24 UTC by rexendevar

Added tentative Windows support. I have not tested it.

2024-05-12 13:24 UTC, rexendevar commented
I don't know how to edit a pull request that's already in progress. Lol

2024-05-14 08:02 UTC, rexendevar commented
it does not work on windows

2024-05-14 09:14 UTC, cfillion requested changes

2024-05-14 09:14 UTC, cfillion commented on Items Editing/ReksEffeks_spleeter/Spleeter2.lua
> +		os.execute(cmd)
This has a command injection vunerability. `filename` is arbitrary data and `cmd` is a shell script. While I don't expect it would be exploited maliciously, this bug can realistically cause the command to fail or behave unexpectedly.

`reaper.ExecProcess` is slightly safer because it only executes the desired program with the given arguments without interpreting the command line as a shell script, unlike `os.execute`. Unexpected inputs would still fail though. External command execution from ReaScript is inherently flawed with all APIs currently available.

Even if the above was fixed, I'm not sure it'd be a good idea to release this because it depends on both spleeter and python to be installed outside of ReaPack, so these script don't "just work" out of the box. There is no error handling either to guide users on what they need to do in case these system dependencies cannot be found.

2024-05-14 09:29 UTC, rexendevar commented on Items Editing/ReksEffeks_spleeter/Spleeter2.lua
> +		os.execute(cmd)
Aside from error handling in the case of Spleeter not being present, is there anything that can be done to fix the issue? I previously tried running it with `reaper.ExecProcess` and the output audio files were simply not functional (see [results of an earlier demo](https://youtu.be/B_TbDpqCfc0)).

2024-05-14 09:33 UTC, rexendevar commented on Items Editing/ReksEffeks_spleeter/Spleeter2.lua
> +		os.execute(cmd)
I do believe that it is extremely useful to provide a way to run Spleeter integrated into the DAW, however. I realize that it is not plug-and-play as most Reaper scripts are but I believe that running a short script from within the DAW is vastly superior to any manual method and therefore is worth the extra dependency.

2024-05-15 01:27 UTC, cfillion commented on Items Editing/ReksEffeks_spleeter/Spleeter2.lua
> +		os.execute(cmd)
Perhaps this could be a Python ReaScript? Python has better process spawning APIs than Lua + ExecProcess. You'd need an API where the program name and its arguments are passed as separate strings in an array, rather than a command line string with injected arbitrary data. (Python has many bugs in REAPER, but it might be fine for this use case.)

```py
command = ['spleeter', 'separate', '-p', 'spleeter:2stems-16kHz', '-o', getPath(filepath), filename]
```

"Program will hang until task is done" isn't great UI either: it's frustrating for users and they may force quit REAPER if it takes too long, potentially losing unsaved data... I'm not familiar with Python, but it probably has ways to spawn and monitor background processes? If it does, could do a little UI with a progress bar eg.

![Example](https://github.com/ReaTeam/ReaScripts/assets/4297676/2f859dfe-afb8-4161-905f-9d07fa7270ad)

2024-05-25 07:54 UTC, closed without merging